=== heron-mc/heron-mc/trunk/apps/previewapp/config/config.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema targetNamespace="http://preview.pdok.nl/1.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:pdok="http://preview.pdok.nl/1.0"
	version="2.1" elementFormDefault="qualified">

	<!-- Root element -->
	<xs:element name="contextCollection" type="pdok:contextCollectionType" />

	<xs:element name="contextItem" type="pdok:contextItemType"
		abstract="true" />
	<xs:element name="contextFolder" type="pdok:contextFolderType"
		substitutionGroup="pdok:contextItem" />
	<xs:element name="context" type="pdok:contextType"
		substitutionGroup="pdok:contextItem" />

	<!-- Sub elements -->
	<xs:element name="layer" type="pdok:layerType" abstract="true" />
	<xs:element name="wmsLayer" type="pdok:wmsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="wmtsLayer" type="pdok:wmtsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="tmsLayer" type="pdok:tmsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="wfsLayer" type="pdok:wfsLayerType"
		substitutionGroup="pdok:layer" />
    <xs:element name="atomLayer" type="pdok:atomLayerType"
   		substitutionGroup="pdok:layer" />

	<!-- Root type -->
	<xs:complexType name="contextCollectionType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
            <xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="baseUrl" type="xs:anyURI" minOccurs="0"/>
			<xs:element name="projection" type="xs:string" />
			<xs:element name="units" type="xs:string" />
			<xs:element name="resolutions" type="xs:string" />
			<xs:element name="maxExtent" type="xs:string" />
			<xs:element name="center" type="xs:string" />
			<xs:element name="xyPrecision" type="xs:double" />
			<xs:element name="zoom" type="xs:integer" />
            <!-- Map with no active baseLayer: default is true -->
            <xs:element name="allOverlays" type="xs:boolean" minOccurs="0" />
			<xs:element name="theme" type="xs:anyURI" minOccurs="0" />
			<xs:element ref="pdok:contextItem" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- ContextItem -->
	<xs:complexType name="contextItemType" abstract="true">
		<xs:sequence>
			<xs:element name="isExpanded" type="xs:boolean" minOccurs="0"/>	
		</xs:sequence>
	</xs:complexType>

	<!-- Folder -->
	<xs:complexType name="contextFolderType">
		<xs:complexContent>
			<xs:extension base="pdok:contextItemType">
				<xs:sequence>
					<xs:element name="title" type="xs:string" />
					<xs:element ref="pdok:contextItem" minOccurs="0"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Context -->
	<xs:complexType name="contextType">
		<xs:complexContent>
			<xs:extension base="pdok:contextItemType">
				<xs:choice>
					<xs:sequence>
						<xs:element name="url" type="xs:anyURI" />
					</xs:sequence>
					<xs:sequence>
						<xs:element name="title" type="xs:string" />
						<xs:element name="baseUrl" type="xs:anyURI" minOccurs = "0"/>
						<xs:element ref="pdok:layer" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Generic Layer -->
	<xs:complexType name="layerType" abstract="true">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="url" type="xs:anyURI" />
			<xs:element name="isBaseLayer" type="xs:boolean" />
			<xs:element name="opacity" type="xs:float" />
			<xs:element name="isTransparent" type="xs:boolean" />
			<xs:element name="isVisible" type="xs:boolean" />
			<xs:element name="minResolution" type="xs:float" minOccurs="0" />
			<xs:element name="maxResolution" type="xs:float" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<!-- WMS -->
	<xs:complexType name="wmsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layers" type="xs:string" />
					<xs:element name="format" type="xs:string" />
					<xs:element name="featureInfoFormat" type="xs:string" />
					<xs:element name="isAlpha" type="xs:boolean" />
					<xs:element name="isSingleTile" type="xs:boolean" />					
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- WMTS -->
	<xs:complexType name="wmtsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layer" type="xs:string" />
					<xs:element name="style" type="xs:string" />
					<xs:element name="matrixSet" type="xs:string" />
					<xs:element name="matrixIds" type="xs:string" />
					<xs:element name="format" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- TMS -->
	<xs:complexType name="tmsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layername" type="xs:string" />
					<xs:element name="type" type="xs:string" />
					<xs:element name="bgColor" type="xs:string" />
					<xs:element name="isSingleTile" type="xs:boolean" />
					<xs:element name="isAlpha" type="xs:boolean" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- WFS -->
	<xs:complexType name="wfsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="wfsVersion" type="xs:string" />
					<xs:element name="wfsFeatureNamespace" type="xs:string" />
                    <xs:element name="wfsFeaturePrefix" type="xs:string" minOccurs="0"/>
					<xs:element name="wfsFeatureType" type="xs:string" />
					<xs:element name="wfsMaxFeatures" type="xs:integer" />
					<xs:element name="wfsGeometryElement" type="xs:string" />
                    <xs:element name="wfsOutputFormat" type="xs:string" minOccurs="0"/>
					<xs:element name="styleMap">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="style" type="pdok:styleType"
									maxOccurs="unbounded">
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

    <!-- Atom feed (GeoRSS) -->
   	<xs:complexType name="atomLayerType">
   		<xs:complexContent>
   			<xs:extension base="pdok:layerType"/>
   		</xs:complexContent>
   	</xs:complexType>

	<xs:complexType name="styleType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" />
						<xs:element name="value" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/tms/top50vector.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
	<context>
		<title>Top50NL Vector</title>
		<tmsLayer>
			<title>Top50NL Vector [tms]</title>
			<url>{baseUrl}tms/</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<minResolution>13.44</minResolution>
			<maxResolution>26.88</maxResolution>
			<layername>top50vector</layername>
			<type>png</type>
			<bgColor>0xffffff</bgColor>
			<isSingleTile>false</isSingleTile>
			<isAlpha>true</isAlpha>
		</tmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/mixed/wetlands.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
    <context>
        <title>Wetlands</title>
        <wmsLayer>
            <title>Wetlands [wms]</title>
            <url>{baseUrl}wetlands/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>wetlands</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <atomLayer>
            <title>Wetlands [atom]</title>
            <url>{baseUrl}wetlands/atom/wetlands.xml</url>
            <isBaseLayer>false</isBaseLayer>
            <isVisible>false</isVisible>
        </atomLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/protocol.xml
<?xml version="1.0" encoding="UTF-8"?>
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">

    <title>Protocol PDOK configuratie - Deze configuratie bevat alle services geordend naar type service</title>
    <baseUrl>http://test.geodata.nationaalgeoregister.nl/</baseUrl>
    <projection>EPSG:28992</projection>
    <units>m</units>
    <resolutions>3440.640,1720.320, 860.160, 430.080, 215.040, 107.520, 53.760, 26.880, 13.440, 6.720, 3.360, 1.680,0.840, 0.420, 0.210, 0.105, 0.0525</resolutions>
    <maxExtent>-285401.920,22598.080,595401.920,903401.920</maxExtent>
    <center>155000,463000</center>
    <xyPrecision>3</xyPrecision>
    <zoom>2</zoom>

    <contextFolder>
        <isExpanded>true</isExpanded>
        <title>TMS</title>
        <context>
            <url>tms/brtachtergrondkaart</url>
        </context>
        <context>
            <url>tms/aan</url>
        </context>
        <context>
            <url>tms/natura2000</url>
        </context>
        <context>
            <url>tms/nok2011</url>
        </context>
        <context>
            <url>tms/top10nl</url>
        </context>
        <context>
            <url>tms/top50vector</url>
        </context>
        <context>
            <url>tms/top50raster</url>
        </context>
        <context>
            <url>tms/top250raster</url>
        </context>
    </contextFolder>
    <contextFolder>
        <isExpanded>true</isExpanded>
        <title>WMTS</title>
        <context>
            <url>wmts/brtachtergrondkaart</url>
        </context>
        <context>
            <url>wmts/aan</url>
        </context>
        <context>
            <url>wmts/kadastralekaart</url>
        </context>
        <context>
            <url>wmts/natura2000</url>
        </context>
        <context>
            <url>wmts/nok2011</url>
        </context>
        <context>
            <url>wmts/top10nl</url>
        </context>
        <context>
            <url>wmts/top50vector</url>
        </context>
        <context>
            <url>wmts/top50raster</url>
        </context>
        <context>
            <url>wmts/top250raster</url>
        </context>
    </contextFolder>
    <contextFolder>
        <isExpanded>true</isExpanded>
        <title>WMS</title>
        <context>
            <url>wms/aan</url>
        </context>
        <context>
            <url>wms/ahn</url>
        </context>
        <context>
            <url>wms/asbestscholenkaart</url>
        </context>
        <context>
            <url>wms/beschermdenatuurmonumenten</url>
        </context>
        <context>
            <url>wms/bestuurlijkegrenzen</url>
        </context>
        <context>
            <url>wms/bevolkingskernen2008</url>
        </context>
        <context>
            <url>wms/bodemgebruik2008</url>
        </context>
        <context>
            <url>wms/cbsvierkanten</url>
        </context>
        <context>
            <url>wms/cultgis</url>
        </context>
        <context>
            <url>wms/dtb</url>
        </context>
        <context>
            <url>wms/fietsknooppuntennetwerk</url>
        </context>
        <context>
            <url>wms/inspireadressen</url>
        </context>
        <context>
            <url>wms/kadastralekaart</url>
        </context>
        <context>
            <url>wms/lawroutes</url>
        </context>
        <context>
            <url>wms/lfroutes</url>
        </context>
        <context>
            <url>wms/streekpaden</url>
        </context>
        <context>
            <url>wms/nationaleparken</url>
        </context>
        <context>
            <url>wms/nhi</url>
        </context>
        <context>
            <url>wms/natura2000</url>
        </context>
        <context>
            <url>wms/nwb</url>
        </context>
        <context>
            <url>wms/nok</url>
        </context>
        <context>
            <url>wms/noordzeekabelsenleidingen</url>
        </context>
        <context>
            <url>wms/maritiemegrenzen</url>
        </context>
        <context>
            <url>wms/noordzeevaarwegmarkeringenrd</url>
        </context>
        <context>
            <url>wms/noordzeewingebieden</url>
        </context>
        <context>
            <url>wms/rdinfo</url>
        </context>
        <context>
            <url>wms/top10nl</url>
        </context>
        <context>
            <url>wms/top50vector</url>
        </context>
        <context>
            <url>wms/top50raster</url>
        </context>
        <context>
            <url>wms/top250raster</url>
        </context>
        <context>
            <url>wms/vin</url>
        </context>
        <context>
            <url>wms/weggegevens</url>
        </context>
        <context>
            <url>wms/wetlands</url>
        </context>
        <context>
            <url>wms/wijkenenbuurten</url>
        </context>
    </contextFolder>
    <contextFolder>
        <isExpanded>true</isExpanded>
        <title>WFS</title>
        <context>
            <url>wfs/nwb</url>
        </context>
    </contextFolder>
</contextCollection>

=== heron-mc/heron-mc/tags/release-0.72/apps/previewapp/config/mixed/top250raster.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
    <context>
        <title>Top250NL Raster</title>
        <tmsLayer>
            <title>Top250NL Raster [tms]</title>
            <url>{baseUrl}tms/</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>53.76</minResolution>
            <maxResolution>107.52</maxResolution>
            <layername>top250raster</layername>
            <type>png</type>
            <bgColor>0xffffff</bgColor>
            <isSingleTile>false</isSingleTile>
            <isAlpha>true</isAlpha>
        </tmsLayer>
        <wmtsLayer>
            <title>Top250NL Raster [wmts]</title>
            <url>{baseUrl}tiles/service/wmts/top50raster?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>53.76</minResolution>
            <maxResolution>107.52</maxResolution>
            <layer>top250raster</layer>
            <style>_null</style>
            <matrixSet>EPSG:28992</matrixSet>
            <matrixIds>
                EPSG:28992:0,EPSG:28992:1,EPSG:28992:2,EPSG:28992:3,EPSG:28992:4,EPSG:28992:5,EPSG:28992:6,EPSG:28992:7,EPSG:28992:8,EPSG:28992:9,EPSG:28992:10,EPSG:28992:11,EPSG:28992:12,EPSG:28992:13,EPSG:28992:14
            </matrixIds>
            <format>image/png</format>
        </wmtsLayer>
        <wmsLayer>
            <title>Top250NL Raster [wms]</title>
            <url>{baseUrl}top250raster/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>53.76</minResolution>
            <maxResolution>107.52</maxResolution>
            <layers>top250raster</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/mixed/achtergrond.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
    <context>
        <isExpanded>false</isExpanded>
        <title>Achtergrond</title>
        <tmsLayer>
            <title>BRTAchtergrondkaart [tms]</title>
            <url>{baseUrl}tms/</url>
            <isBaseLayer>true</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>true</isVisible>
            <minResolution>0.21</minResolution>
            <layername>brtachtergrondkaart</layername>
            <type>png</type>
            <bgColor>0xffffff</bgColor>
            <isSingleTile>false</isSingleTile>
            <isAlpha>true</isAlpha>
        </tmsLayer>
        <tmsLayer>
            <title>Top10NL [tms]</title>
            <url>{baseUrl}tms/</url>
            <isBaseLayer>true</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>0.21</minResolution>
            <maxResolution>13.44</maxResolution>
            <layername>top10nl</layername>
            <type>png</type>
            <bgColor>0xffffff</bgColor>
            <isSingleTile>false</isSingleTile>
            <isAlpha>true</isAlpha>
        </tmsLayer>
        <tmsLayer>
            <title>Top50NL Vector [tms]</title>
            <url>{baseUrl}tms/</url>
            <isBaseLayer>true</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>13.44</minResolution>
            <maxResolution>26.88</maxResolution>
            <layername>top50vector</layername>
            <type>png</type>
            <bgColor>0xffffff</bgColor>
            <isSingleTile>false</isSingleTile>
            <isAlpha>true</isAlpha>
        </tmsLayer>
        <tmsLayer>
            <title>Top250NL Raster [tms]</title>
            <url>{baseUrl}tms/</url>
            <isBaseLayer>true</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>53.76</minResolution>
            <maxResolution>107.52</maxResolution>
            <layername>top250raster</layername>
            <type>png</type>
            <bgColor>0xffffff</bgColor>
            <isSingleTile>false</isSingleTile>
            <isAlpha>true</isAlpha>
        </tmsLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/mixed/top10nl.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
    <context>
        <title>Top10NL</title>
        <tmsLayer>
            <title>Top10NL [tms]</title>
            <url>{baseUrl}tms/</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>0.21</minResolution>
            <maxResolution>13.44</maxResolution>
            <layername>top10nl</layername>
            <type>png</type>
            <bgColor>0xffffff</bgColor>
            <isSingleTile>false</isSingleTile>
            <isAlpha>true</isAlpha>
        </tmsLayer>
        <wmtsLayer>
            <title>Top10NL [wmts]</title>
            <url>{baseUrl}tiles/service/wmts/top10nl?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>0.21</minResolution>
            <maxResolution>13.44</maxResolution>
            <layer>top10nl</layer>
            <style>_null</style>
            <matrixSet>EPSG:28992</matrixSet>
            <matrixIds>
                EPSG:28992:0,EPSG:28992:1,EPSG:28992:2,EPSG:28992:3,EPSG:28992:4,EPSG:28992:5,EPSG:28992:6,EPSG:28992:7,EPSG:28992:8,EPSG:28992:9,EPSG:28992:10,EPSG:28992:11,EPSG:28992:12,EPSG:28992:13,EPSG:28992:14
            </matrixIds>
            <format>image/png</format>
        </wmtsLayer>
        <wmsLayer>
            <title>Geografische namen [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>geo_labels</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Functionele gebieden [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>functioneelgebied_labels</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Inrichtingselement - punten [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>inrichtingselement_punten</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Spoorbaandeel - lijnen [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>spoorbaandeel_lijnen</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Inrichtingselement - lijnen [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>inrichtingselement_lijnen</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Waterdeel - lijnen [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>waterdeel_lijnen</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Gebouwen [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>gebouwen</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Waterdeel - vlakken [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>waterdeel_vlakken</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Wegdeelvlakken [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>wegdeelvlakken</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Terreinen [wms]</title>
            <url>{baseUrl}top10nl/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>terreinen</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <atomLayer>
            <title>Top10NL [atom]</title>
            <url>{baseUrl}top10nl/atom/top10nl.xml</url>
            <isBaseLayer>false</isBaseLayer>
            <isVisible>false</isVisible>
        </atomLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/tags/release-0.71/apps/previewapp/config/mixed/inspireadressen.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
    <context>
        <title>Inspireadressen (=BAG)</title>
        <wmsLayer>
            <title>Adressen [wms]</title>
            <url>{baseUrl}inspireadressen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>6.72</maxResolution>
            <layers>inspireadressen</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <atomLayer>
            <title>Inspireadressen (=BAG) [atom]</title>
            <url>{baseUrl}inspireadressen/atom/inspireadressen.xml</url>
            <isBaseLayer>false</isBaseLayer>
            <isVisible>false</isVisible>
        </atomLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/tms/top50raster.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
	<context>
		<title>Top50NL Raster</title>
		<tmsLayer>
			<title>Top50NL Raster [tms]</title>
			<url>{baseUrl}tms/</url>
			<isBaseLayer>true</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<minResolution>13.44</minResolution>
			<maxResolution>26.88</maxResolution>
			<layername>top50raster</layername>
			<type>png</type>
			<bgColor>0xffffff</bgColor>
			<isSingleTile>false</isSingleTile>
			<isAlpha>true</isAlpha>
		</tmsLayer>
	</context>
</contextCollection>
