=== heron-mc/heron-mc/trunk/apps/previewapp/config/config.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema targetNamespace="http://preview.pdok.nl/1.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:pdok="http://preview.pdok.nl/1.0"
	version="2.1" elementFormDefault="qualified">

	<!-- Root element -->
	<xs:element name="contextCollection" type="pdok:contextCollectionType" />

	<xs:element name="contextItem" type="pdok:contextItemType"
		abstract="true" />
	<xs:element name="contextFolder" type="pdok:contextFolderType"
		substitutionGroup="pdok:contextItem" />
	<xs:element name="context" type="pdok:contextType"
		substitutionGroup="pdok:contextItem" />

	<!-- Sub elements -->
	<xs:element name="layer" type="pdok:layerType" abstract="true" />
	<xs:element name="wmsLayer" type="pdok:wmsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="wmtsLayer" type="pdok:wmtsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="tmsLayer" type="pdok:tmsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="wfsLayer" type="pdok:wfsLayerType"
		substitutionGroup="pdok:layer" />
    <xs:element name="atomLayer" type="pdok:atomLayerType"
   		substitutionGroup="pdok:layer" />

	<!-- Root type -->
	<xs:complexType name="contextCollectionType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
            <xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="baseUrl" type="xs:anyURI" minOccurs="0"/>
			<xs:element name="projection" type="xs:string" />
			<xs:element name="units" type="xs:string" />
			<xs:element name="resolutions" type="xs:string" />
			<xs:element name="maxExtent" type="xs:string" />
			<xs:element name="center" type="xs:string" />
			<xs:element name="xyPrecision" type="xs:double" />
			<xs:element name="zoom" type="xs:integer" />
            <!-- Map with no active baseLayer: default is true -->
            <xs:element name="allOverlays" type="xs:boolean" minOccurs="0" />
			<xs:element name="theme" type="xs:anyURI" minOccurs="0" />
			<xs:element ref="pdok:contextItem" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- ContextItem -->
	<xs:complexType name="contextItemType" abstract="true">
		<xs:sequence>
			<xs:element name="isExpanded" type="xs:boolean" minOccurs="0"/>	
		</xs:sequence>
	</xs:complexType>

	<!-- Folder -->
	<xs:complexType name="contextFolderType">
		<xs:complexContent>
			<xs:extension base="pdok:contextItemType">
				<xs:sequence>
					<xs:element name="title" type="xs:string" />
					<xs:element ref="pdok:contextItem" minOccurs="0"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Context -->
	<xs:complexType name="contextType">
		<xs:complexContent>
			<xs:extension base="pdok:contextItemType">
				<xs:choice>
					<xs:sequence>
						<xs:element name="url" type="xs:anyURI" />
					</xs:sequence>
					<xs:sequence>
						<xs:element name="title" type="xs:string" />
						<xs:element name="baseUrl" type="xs:anyURI" minOccurs = "0"/>
						<xs:element ref="pdok:layer" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Generic Layer -->
	<xs:complexType name="layerType" abstract="true">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="url" type="xs:anyURI" />
			<xs:element name="isBaseLayer" type="xs:boolean" />
			<xs:element name="opacity" type="xs:float" />
			<xs:element name="isTransparent" type="xs:boolean" />
			<xs:element name="isVisible" type="xs:boolean" />
			<xs:element name="minResolution" type="xs:float" minOccurs="0" />
			<xs:element name="maxResolution" type="xs:float" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<!-- WMS -->
	<xs:complexType name="wmsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layers" type="xs:string" />
					<xs:element name="format" type="xs:string" />
					<xs:element name="featureInfoFormat" type="xs:string" />
					<xs:element name="isAlpha" type="xs:boolean" />
					<xs:element name="isSingleTile" type="xs:boolean" />					
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- WMTS -->
	<xs:complexType name="wmtsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layer" type="xs:string" />
					<xs:element name="style" type="xs:string" />
					<xs:element name="matrixSet" type="xs:string" />
					<xs:element name="matrixIds" type="xs:string" />
					<xs:element name="format" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- TMS -->
	<xs:complexType name="tmsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layername" type="xs:string" />
					<xs:element name="type" type="xs:string" />
					<xs:element name="bgColor" type="xs:string" />
					<xs:element name="isSingleTile" type="xs:boolean" />
					<xs:element name="isAlpha" type="xs:boolean" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- WFS -->
	<xs:complexType name="wfsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="wfsVersion" type="xs:string" />
					<xs:element name="wfsFeatureNamespace" type="xs:string" />
                    <xs:element name="wfsFeaturePrefix" type="xs:string" minOccurs="0"/>
					<xs:element name="wfsFeatureType" type="xs:string" />
					<xs:element name="wfsMaxFeatures" type="xs:integer" />
					<xs:element name="wfsGeometryElement" type="xs:string" />
                    <xs:element name="wfsOutputFormat" type="xs:string" minOccurs="0"/>
					<xs:element name="styleMap">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="style" type="pdok:styleType"
									maxOccurs="unbounded">
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

    <!-- Atom feed (GeoRSS) -->
   	<xs:complexType name="atomLayerType">
   		<xs:complexContent>
   			<xs:extension base="pdok:layerType"/>
   		</xs:complexContent>
   	</xs:complexType>

	<xs:complexType name="styleType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" />
						<xs:element name="value" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== heron-mc/heron-mc/tags/release-1.0.5/apps/pdokviewer/config/epsg25831.xml
<?xml version="1.0"?>
<contextCollection xmlns="http://preview.pdok.nl/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
  <title>PDOK configuratie in EPSG:25831 projectie met RWS tileschema - Deze configuratie bevat alleen relevante services</title>
  <baseUrl>http://geodata.nationaalgeoregister.nl/</baseUrl>
  <projection>EPSG:25831</projection>
  <units>m</units>
  <resolutions>2800,1400,700,280,140,70,28,21,14,7,2.8,1.4</resolutions>
  <maxExtent>-2404683.40738879,3997657.58466454,3663603.36143588,8032006.61513546</maxExtent>
  <center>629459.97702355,6014832.09990000</center>
  <xyPrecision>3</xyPrecision>
  <zoom>2</zoom>
  <allOverlays>true</allOverlays>
  <context>
    <isExpanded>false</isExpanded>
    <title>Achtergrond</title>
    <tmsLayer>
      <title>BRTAchtergrondkaart [tms]</title>
      <url>{baseUrl}tms/</url>
      <isBaseLayer>true</isBaseLayer>
      <opacity>0.7</opacity>
      <isTransparent>true</isTransparent>
      <isVisible>true</isVisible>
      <minResolution>0.21</minResolution>
      <layername>brtachtergrondkaart@EPSG:25831:RWS@png</layername>
      <type>png</type>
      <bgColor>0xffffff</bgColor>
      <isSingleTile>false</isSingleTile>
      <isAlpha>true</isAlpha>
    </tmsLayer>
  </context>
  <contextFolder>
    <isExpanded>true</isExpanded>
    <title>PDOK Services</title>
    <context>
      <title>BRTAchtergrondkaart</title>
      <tmsLayer>
        <title>BRTAchtergrondkaart [tms/png8]</title>
        <url>{baseUrl}tms/</url>
        <isBaseLayer>true</isBaseLayer>
        <opacity>0.7</opacity>
        <isTransparent>true</isTransparent>
        <isVisible>true</isVisible>
        <minResolution>0.21</minResolution>
        <layername>brtachtergrondkaart@EPSG:25831:RWS@png8</layername>
        <type>png8</type>
        <bgColor>0xffffff</bgColor>
        <isSingleTile>false</isSingleTile>
        <isAlpha>true</isAlpha>
      </tmsLayer>
      <wmtsLayer>
        <title>BRTAchtergrondkaart [wmts/png8]</title>
        <url>{baseUrl}tiles/service/wmts/brtachtergrond?</url>
        <isBaseLayer>true</isBaseLayer>
        <opacity>0.7</opacity>
        <isTransparent>true</isTransparent>
        <isVisible>false</isVisible>
        <minResolution>0.21</minResolution>
        <layer>brtachtergrondkaart</layer>
        <style>_null</style>
        <matrixSet>EPSG:25831:RWS</matrixSet>
        <matrixIds>EPSG:25831:RWS:0,EPSG:25831:RWS:1,EPSG:25831:RWS:2,EPSG:25831:RWS:3,EPSG:25831:RWS:4,EPSG:25831:RWS:5,EPSG:25831:RWS:6,EPSG:25831:RWS:7,EPSG:25831:RWS:8,EPSG:25831:RWS:9,EPSG:25831:RWS:10,EPSG:25831:RWS:11</matrixIds>
        <format>image/png8</format>
      </wmtsLayer>
      <wmtsLayer>
        <title>BRTAchtergrondkaart [wmts/png]</title>
        <url>{baseUrl}tiles/service/wmts/brtachtergrond?</url>
        <isBaseLayer>true</isBaseLayer>
        <opacity>0.7</opacity>
        <isTransparent>true</isTransparent>
        <isVisible>false</isVisible>
        <minResolution>0.21</minResolution>
        <layer>brtachtergrondkaart</layer>
        <style>_null</style>
        <matrixSet>EPSG:25831:RWS</matrixSet>
        <matrixIds>EPSG:25831:RWS:0,EPSG:25831:RWS:1,EPSG:25831:RWS:2,EPSG:25831:RWS:3,EPSG:25831:RWS:4,EPSG:25831:RWS:5,EPSG:25831:RWS:6,EPSG:25831:RWS:7,EPSG:25831:RWS:8,EPSG:25831:RWS:9,EPSG:25831:RWS:10,EPSG:25831:RWS:11</matrixIds>
        <format>image/png</format>
      </wmtsLayer>
    </context>
    <context>
      <title>Bestuurlijke grenzen 2012</title>
      <wmsLayer>
        <title>Gemeentegrenzen 2012 [wms]</title>
        <url>{baseUrl}bestuurlijkegrenzen/wms?</url>
        <isBaseLayer>false</isBaseLayer>
        <opacity>0.7</opacity>
        <isTransparent>true</isTransparent>
        <isVisible>false</isVisible>
        <layers>gemeenten_2012</layers>
        <format>image/png</format>
        <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
        <isAlpha>true</isAlpha>
        <isSingleTile>true</isSingleTile>
      </wmsLayer>
      <wmsLayer>
        <title>Provinciegrenzen 2012 [wms]</title>
        <url>{baseUrl}bestuurlijkegrenzen/wms?</url>
        <isBaseLayer>false</isBaseLayer>
        <opacity>0.7</opacity>
        <isTransparent>true</isTransparent>
        <isVisible>false</isVisible>
        <layers>provincies_2012</layers>
        <format>image/png</format>
        <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
        <isAlpha>true</isAlpha>
        <isSingleTile>true</isSingleTile>
      </wmsLayer>
      <wmsLayer>
        <title>Landsgrens 2012 [wms]</title>
        <url>{baseUrl}bestuurlijkegrenzen/wms?</url>
        <isBaseLayer>false</isBaseLayer>
        <opacity>0.7</opacity>
        <isTransparent>true</isTransparent>
        <isVisible>false</isVisible>
        <layers>landsgrens_2012</layers>
        <format>image/png</format>
        <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
        <isAlpha>true</isAlpha>
        <isSingleTile>true</isSingleTile>
      </wmsLayer>
      <atomLayer>
        <title>Bestuurlijke Grenzen [atom]</title>
        <url>{baseUrl}bestuurlijkegrenzen/atom/bestuurlijkegrenzen.xml</url>
        <isBaseLayer>false</isBaseLayer>
        <isVisible>false</isVisible>
      </atomLayer>
    </context>
  </contextFolder>
</contextCollection>

=== heron-mc/heron-mc/tags/release-0.71/apps/previewapp/config/mixed/bestuurlijkegrenzen.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
    <context>
        <title>Bestuurlijke grenzen 2012</title>
        <wmsLayer>
            <title>Gemeentegrenzen 2012 [wms]</title>
            <url>{baseUrl}bestuurlijkegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>gemeenten_2012</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Provinciegrenzen 2012 [wms]</title>
            <url>{baseUrl}bestuurlijkegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>provincies_2012</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Landsgrens 2012 [wms]</title>
            <url>{baseUrl}bestuurlijkegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>landsgrens_2012</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <atomLayer>
            <title>Bestuurlijke Grenzen [atom]</title>
            <url>{baseUrl}bestuurlijkegrenzen/atom/bestuurlijkegrenzen.xml</url>
            <isBaseLayer>false</isBaseLayer>
            <isVisible>false</isVisible>
        </atomLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/tms/natura2000.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
	<context>
		<title>Natura 2000</title>
		<tmsLayer>
			<title>Natura 2000 [tms]</title>
			<url>{baseUrl}tms/</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<minResolution>0.21</minResolution>
			<layername>natura2000</layername>
			<type>png</type>
			<bgColor>0xffffff</bgColor>
			<isSingleTile>false</isSingleTile>
			<isAlpha>true</isAlpha>
		</tmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/tags/release-1.0.4/apps/previewapp/config/mixed/natura2000.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
    <context>
        <title>Natura 2000</title>
        <tmsLayer>
            <title>Natura 2000 [tms]</title>
            <url>{baseUrl}tms/</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>0.21</minResolution>
            <layername>natura2000</layername>
            <type>png</type>
            <bgColor>0xffffff</bgColor>
            <isSingleTile>false</isSingleTile>
            <isAlpha>true</isAlpha>
        </tmsLayer>
        <wmtsLayer>
            <title>Natura 2000 [wmts]</title>
            <url>{baseUrl}tiles/service/wmts/natura2000?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>0.21</minResolution>
            <layer>natura2000</layer>
            <style>_null</style>
            <matrixSet>EPSG:28992</matrixSet>
            <matrixIds>
                EPSG:28992:0,EPSG:28992:1,EPSG:28992:2,EPSG:28992:3,EPSG:28992:4,EPSG:28992:5,EPSG:28992:6,EPSG:28992:7,EPSG:28992:8,EPSG:28992:9,EPSG:28992:10,EPSG:28992:11,EPSG:28992:12,EPSG:28992:13,EPSG:28992:14
            </matrixIds>
            <format>image/png</format>
        </wmtsLayer>
        <wmsLayer>
            <title>Natura 2000 [wms]</title>
            <url>{baseUrl}natura2000/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>natura2000</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <atomLayer>
            <title>Natura 2000 [atom]</title>
            <url>{baseUrl}natura2000/atom/natura2000.xml</url>
            <isBaseLayer>false</isBaseLayer>
            <isVisible>false</isVisible>
        </atomLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/tms/brtachtergrondkaart.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
	<context>
		<title>BRTAchtergrondkaart</title>
		<tmsLayer>
			<title>BRTAchtergrondkaart [tms]</title>
			<url>{baseUrl}tms/</url>
			<isBaseLayer>true</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>true</isVisible>
			<minResolution>0.21</minResolution>
			<layername>brtachtergrondkaart</layername>
			<type>png</type>
			<bgColor>0xffffff</bgColor>
			<isSingleTile>false</isSingleTile>
			<isAlpha>true</isAlpha>
		</tmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/apps/previewapp/config/wms/wijkenenbuurten.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
	<contextFolder>
		<title>Wijken en buurten</title>
		<context>
			<title>2011</title>
			<wmsLayer>
				<title>CBS Buurten 2011 [wms]</title>
				<url>{baseUrl}wijkenbuurten2011/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>26.88</maxResolution>
				<layers>cbs_buurten_2011</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>CBS Wijken 2011 [wms]</title>
				<url>{baseUrl}wijkenbuurten2011/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>107.52</maxResolution>
				<layers>cbs_wijken_2011</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Gemeenten 2011 [wms]</title>
				<url>{baseUrl}wijkenbuurten2011/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<layers>gemeenten2011</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
		</context>
		<context>
			<title>2010</title>
			<wmsLayer>
				<title>CBS Buurten 2010 [wms]</title>
				<url>{baseUrl}wijkenbuurten2010/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>26.88</maxResolution>
				<layers>cbs_buurten_2010</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>CBS Wijken 2010 [wms]</title>
				<url>{baseUrl}wijkenbuurten2010/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>107.52</maxResolution>
				<layers>cbs_wijken_2010</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Gemeenten 2010 [wms]</title>
				<url>{baseUrl}wijkenbuurten2010/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<layers>gemeenten2010</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
		</context>
		<context>
			<title>2009</title>
			<wmsLayer>
				<title>CBS Buurten 2009 [wms]</title>
				<url>{baseUrl}wijkenbuurten2009/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>26.88</maxResolution>
				<layers>cbs_buurten_2009</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>CBS Wijken 2009 [wms]</title>
				<url>{baseUrl}wijkenbuurten2009/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>107.52</maxResolution>
				<layers>cbs_wijken_2009</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Gemeenten 2009 [wms]</title>
				<url>{baseUrl}wijkenbuurten2009/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<layers>gemeenten2009</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
		</context>
	</contextFolder>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/wms/noordzeekabelsenleidingen.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
	<context>
		<title>Noordzee Kabels en Leidingen</title>
		<wmsLayer>
			<title>Kabels [wms]</title>
			<url>{baseUrl}noordzeekabelsenleidingen/wms?</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<maxResolution>53.76</maxResolution>
			<layers>kabels</layers>
			<format>image/png</format>
			<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
			<isAlpha>true</isAlpha>
			<isSingleTile>true</isSingleTile>
		</wmsLayer>
		<wmsLayer>
			<title>Leidingen [wms]</title>
			<url>{baseUrl}noordzeekabelsenleidingen/wms?</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<layers>leidingen</layers>
			<format>image/png</format>
			<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
			<isAlpha>true</isAlpha>
			<isSingleTile>true</isSingleTile>
		</wmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/wmts/top50vector.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
	<context>
		<title>Top50NL Vector</title>
		<wmtsLayer>
			<title>Top50NL Vector [wmts]</title>
			<url>{baseUrl}tiles/service/wmts/top50vector?</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<minResolution>13.44</minResolution>
			<maxResolution>26.88</maxResolution>
			<layer>top50vector</layer>
			<style>_null</style>
			<matrixSet>EPSG:28992</matrixSet>
			<matrixIds>EPSG:28992:0,EPSG:28992:1,EPSG:28992:2,EPSG:28992:3,EPSG:28992:4,EPSG:28992:5,EPSG:28992:6,EPSG:28992:7,EPSG:28992:8,EPSG:28992:9,EPSG:28992:10,EPSG:28992:11,EPSG:28992:12,EPSG:28992:13,EPSG:28992:14</matrixIds>
			<format>image/png</format>
		</wmtsLayer>
	</context>
</contextCollection>
