=== heron-mc/heron-mc/trunk/apps/previewapp/config/config.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema targetNamespace="http://preview.pdok.nl/1.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:pdok="http://preview.pdok.nl/1.0"
	version="2.1" elementFormDefault="qualified">

	<!-- Root element -->
	<xs:element name="contextCollection" type="pdok:contextCollectionType" />

	<xs:element name="contextItem" type="pdok:contextItemType"
		abstract="true" />
	<xs:element name="contextFolder" type="pdok:contextFolderType"
		substitutionGroup="pdok:contextItem" />
	<xs:element name="context" type="pdok:contextType"
		substitutionGroup="pdok:contextItem" />

	<!-- Sub elements -->
	<xs:element name="layer" type="pdok:layerType" abstract="true" />
	<xs:element name="wmsLayer" type="pdok:wmsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="wmtsLayer" type="pdok:wmtsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="tmsLayer" type="pdok:tmsLayerType"
		substitutionGroup="pdok:layer" />
	<xs:element name="wfsLayer" type="pdok:wfsLayerType"
		substitutionGroup="pdok:layer" />
    <xs:element name="atomLayer" type="pdok:atomLayerType"
   		substitutionGroup="pdok:layer" />

	<!-- Root type -->
	<xs:complexType name="contextCollectionType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
            <xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="baseUrl" type="xs:anyURI" minOccurs="0"/>
			<xs:element name="projection" type="xs:string" />
			<xs:element name="units" type="xs:string" />
			<xs:element name="resolutions" type="xs:string" />
			<xs:element name="maxExtent" type="xs:string" />
			<xs:element name="center" type="xs:string" />
			<xs:element name="xyPrecision" type="xs:double" />
			<xs:element name="zoom" type="xs:integer" />
            <!-- Map with no active baseLayer: default is true -->
            <xs:element name="allOverlays" type="xs:boolean" minOccurs="0" />
			<xs:element name="theme" type="xs:anyURI" minOccurs="0" />
			<xs:element ref="pdok:contextItem" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- ContextItem -->
	<xs:complexType name="contextItemType" abstract="true">
		<xs:sequence>
			<xs:element name="isExpanded" type="xs:boolean" minOccurs="0"/>	
		</xs:sequence>
	</xs:complexType>

	<!-- Folder -->
	<xs:complexType name="contextFolderType">
		<xs:complexContent>
			<xs:extension base="pdok:contextItemType">
				<xs:sequence>
					<xs:element name="title" type="xs:string" />
					<xs:element ref="pdok:contextItem" minOccurs="0"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Context -->
	<xs:complexType name="contextType">
		<xs:complexContent>
			<xs:extension base="pdok:contextItemType">
				<xs:choice>
					<xs:sequence>
						<xs:element name="url" type="xs:anyURI" />
					</xs:sequence>
					<xs:sequence>
						<xs:element name="title" type="xs:string" />
						<xs:element name="baseUrl" type="xs:anyURI" minOccurs = "0"/>
						<xs:element ref="pdok:layer" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Generic Layer -->
	<xs:complexType name="layerType" abstract="true">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="url" type="xs:anyURI" />
			<xs:element name="isBaseLayer" type="xs:boolean" />
			<xs:element name="opacity" type="xs:float" />
			<xs:element name="isTransparent" type="xs:boolean" />
			<xs:element name="isVisible" type="xs:boolean" />
			<xs:element name="minResolution" type="xs:float" minOccurs="0" />
			<xs:element name="maxResolution" type="xs:float" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<!-- WMS -->
	<xs:complexType name="wmsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layers" type="xs:string" />
					<xs:element name="format" type="xs:string" />
					<xs:element name="featureInfoFormat" type="xs:string" />
					<xs:element name="isAlpha" type="xs:boolean" />
					<xs:element name="isSingleTile" type="xs:boolean" />					
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- WMTS -->
	<xs:complexType name="wmtsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layer" type="xs:string" />
					<xs:element name="style" type="xs:string" />
					<xs:element name="matrixSet" type="xs:string" />
					<xs:element name="matrixIds" type="xs:string" />
					<xs:element name="format" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- TMS -->
	<xs:complexType name="tmsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="layername" type="xs:string" />
					<xs:element name="type" type="xs:string" />
					<xs:element name="bgColor" type="xs:string" />
					<xs:element name="isSingleTile" type="xs:boolean" />
					<xs:element name="isAlpha" type="xs:boolean" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- WFS -->
	<xs:complexType name="wfsLayerType">
		<xs:complexContent>
			<xs:extension base="pdok:layerType">
				<xs:sequence>
					<xs:element name="wfsVersion" type="xs:string" />
					<xs:element name="wfsFeatureNamespace" type="xs:string" />
                    <xs:element name="wfsFeaturePrefix" type="xs:string" minOccurs="0"/>
					<xs:element name="wfsFeatureType" type="xs:string" />
					<xs:element name="wfsMaxFeatures" type="xs:integer" />
					<xs:element name="wfsGeometryElement" type="xs:string" />
                    <xs:element name="wfsOutputFormat" type="xs:string" minOccurs="0"/>
					<xs:element name="styleMap">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="style" type="pdok:styleType"
									maxOccurs="unbounded">
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

    <!-- Atom feed (GeoRSS) -->
   	<xs:complexType name="atomLayerType">
   		<xs:complexContent>
   			<xs:extension base="pdok:layerType"/>
   		</xs:complexContent>
   	</xs:complexType>

	<xs:complexType name="styleType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" />
						<xs:element name="value" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/wms/asbestscholenkaart.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
	<context>
		<title>Asbest Scholenkaart</title>
		<wmsLayer>
			<title>Asbest scholenkaart [wms]</title>
			<url>{baseUrl}asbestscholenkaart/wms?</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<maxResolution>26.88</maxResolution>
			<layers>asbestscholenkaart</layers>
			<format>image/png</format>
			<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
			<isAlpha>true</isAlpha>
			<isSingleTile>true</isSingleTile>
		</wmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/mixed/nok.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
    <contextFolder>
        <title>Natuurmeting Op Kaart (NOK)</title>
        <context>
            <title>2011</title>
            <tmsLayer>
                <title>NOK 2011 [tms]</title>
                <url>{baseUrl}tms/</url>
                <isBaseLayer>true</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <minResolution>0.21</minResolution>
                <layername>nok2011</layername>
                <type>png</type>
                <bgColor>0xffffff</bgColor>
                <isSingleTile>false</isSingleTile>
                <isAlpha>true</isAlpha>
            </tmsLayer>
            <wmtsLayer>
                <title>NOK 2011 [wmts]</title>
                <url>{baseUrl}tiles/service/wmts/nok2011?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <minResolution>0.21</minResolution>
                <layer>nok2011</layer>
                <style>_null</style>
                <matrixSet>EPSG:28992</matrixSet>
                <matrixIds>
                    EPSG:28992:0,EPSG:28992:1,EPSG:28992:2,EPSG:28992:3,EPSG:28992:4,EPSG:28992:5,EPSG:28992:6,EPSG:28992:7,EPSG:28992:8,EPSG:28992:9,EPSG:28992:10,EPSG:28992:11,EPSG:28992:12,EPSG:28992:13,EPSG:28992:14
                </matrixIds>
                <format>image/png</format>
            </wmtsLayer>
            <wmsLayer>
                <title>Begrenzing 2011 [wms]</title>
                <url>{baseUrl}nok2011/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>begrenzing</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
            <wmsLayer>
                <title>EHS 2011 [wms]</title>
                <url>{baseUrl}nok2011/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>planologischeehs</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
            <wmsLayer>
                <title>Verwerving inrichting 2011 [wms]</title>
                <url>{baseUrl}nok2011/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>verwervinginrichting</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
        </context>
        <context>
            <title>2010</title>
            <wmsLayer>
                <title>EHS 2010 [wms]</title>
                <url>{baseUrl}nok2010/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>ehs</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
            <wmsLayer>
                <title>RodS 2010 [wms]</title>
                <url>{baseUrl}nok2010/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>rods</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
            <wmsLayer>
                <title>BBL-bezit buiten EHS en RodS 2010 [wms]</title>
                <url>{baseUrl}nok2010/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>bblbuitenbegrenzing</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
        </context>
        <context>
            <title>2007</title>
            <wmsLayer>
                <title>EHS 2007 [wms]</title>
                <url>{baseUrl}nok2007/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>ehs</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
            <wmsLayer>
                <title>RodS 2007 [wms]</title>
                <url>{baseUrl}nok2007/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>rods</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
            <wmsLayer>
                <title>BBL-bezit buiten EHS en RodS 2007 [wms]</title>
                <url>{baseUrl}nok2007/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <layers>bblbuitenbegrenzing</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
        </context>
    </contextFolder>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/mixed/brtachtergrondkaart.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
    <context>
        <title>BRTAchtergrondkaart</title>
        <tmsLayer>
            <title>BRTAchtergrondkaart [tms]</title>
            <url>{baseUrl}tms/</url>
            <isBaseLayer>true</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>true</isVisible>
            <minResolution>0.21</minResolution>
            <layername>brtachtergrondkaart</layername>
            <type>png</type>
            <bgColor>0xffffff</bgColor>
            <isSingleTile>false</isSingleTile>
            <isAlpha>true</isAlpha>
        </tmsLayer>
        <wmtsLayer>
            <title>BRTAchtergrondkaart [wmts]</title>
            <url>{baseUrl}tiles/service/wmts/brtachtergrond?</url>
            <isBaseLayer>true</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <minResolution>0.21</minResolution>
            <layer>brtachtergrondkaart</layer>
            <style>_null</style>
            <matrixSet>EPSG:28992</matrixSet>
            <matrixIds>
                EPSG:28992:0,EPSG:28992:1,EPSG:28992:2,EPSG:28992:3,EPSG:28992:4,EPSG:28992:5,EPSG:28992:6,EPSG:28992:7,EPSG:28992:8,EPSG:28992:9,EPSG:28992:10,EPSG:28992:11,EPSG:28992:12,EPSG:28992:13,EPSG:28992:14
            </matrixIds>
            <format>image/png</format>
        </wmtsLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/wms/top250raster.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
	<context>
		<title>Top250NL Raster</title>
		<wmsLayer>
			<title>Top250NL Raster [wms]</title>
			<url>{baseUrl}top250raster/wms?</url>
			<isBaseLayer>true</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<minResolution>53.76</minResolution>
			<maxResolution>107.52</maxResolution>
			<layers>top250raster</layers>
			<format>image/png</format>
			<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
			<isAlpha>true</isAlpha>
			<isSingleTile>true</isSingleTile>
		</wmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/mixed/maritiemegrenzen.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
    <context>
        <title>Noordzee Maritieme Grenzen</title>
        <wmsLayer>
            <title>Nederlandse basislijn [wms]</title>
            <url>{baseUrl}maritiemegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <maxResolution>53.76</maxResolution>
            <layers>nederlandsebasislijn</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Nautische 1 mijl grens [wms]</title>
            <url>{baseUrl}maritiemegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>nautische01mijlgrens</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Nautische 3 mijl grens [wms]</title>
            <url>{baseUrl}maritiemegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>nautische03mijlgrens</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Nautische 6 mijl grens [wms]</title>
            <url>{baseUrl}maritiemegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>nautische06mijlgrens</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Nautische 12 mijl grens [wms]</title>
            <url>{baseUrl}maritiemegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>nautische12mijlgrens</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <wmsLayer>
            <title>Nautische 24 mijl grens [wms]</title>
            <url>{baseUrl}maritiemegrenzen/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>nautische24mijlgrens</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/mixed/vin.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
    <context>
        <title>Vaarkenmerken in Nederland (VIN)</title>
        <wmsLayer>
            <title>Bevaarbaarheid [wms]</title>
            <url>{baseUrl}vin/wms?</url>
            <isBaseLayer>false</isBaseLayer>
            <opacity>0.7</opacity>
            <isTransparent>true</isTransparent>
            <isVisible>false</isVisible>
            <layers>bevaarbaarheid</layers>
            <format>image/png</format>
            <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
            <isAlpha>true</isAlpha>
            <isSingleTile>true</isSingleTile>
        </wmsLayer>
        <atomLayer>
            <title>Bevaarbaarheid [atom]</title>
            <url>{baseUrl}vin/atom/vin.xml</url>
            <isBaseLayer>false</isBaseLayer>
            <isVisible>false</isVisible>
        </atomLayer>
    </context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/wms/natura2000.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://preview.pdok.nl/1.0 ../config.xsd">
	<context>
			<title>Natura 2000</title>
			<wmsLayer>
				<title>Natura 2000 [wms]</title>
				<url>{baseUrl}natura2000/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<layers>natura2000</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>	
	</context>
</contextCollection>

=== heron-mc/heron-mc/trunk/apps/previewapp/config/mixed/inspire.xml
<contextCollection xmlns="http://preview.pdok.nl/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://preview.pdok.nl/1.0 config.xsd ">
    <contextFolder>
        <isExpanded>false</isExpanded>
        <title>INSPIRE (Harmonized Data)</title>
        <context>
            <title>Addresses (AD)</title>
            <wmsLayer>
                <title>AD.Address [wms]</title>
                <url>{baseUrl}inspire/ad/wms?</url>
                <isBaseLayer>false</isBaseLayer>
                <opacity>0.7</opacity>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <maxResolution>6.72</maxResolution>
                <layers>AD.Address</layers>
                <format>image/png</format>
                <featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
                <isAlpha>true</isAlpha>
                <isSingleTile>true</isSingleTile>
            </wmsLayer>
            <wfsLayer>
                <title>AD.Address [wfs]</title>
                <url>{baseUrl}inspire/ad/wfs?</url>
                <isBaseLayer>false</isBaseLayer>
                <isTransparent>true</isTransparent>
                <isVisible>false</isVisible>
                <maxResolution>6.72</maxResolution>
                <wfsVersion>1.1.0</wfsVersion>
                <wfsFeatureNamespace>urn:x-inspire:specification:gmlas:Addresses:3.0</wfsFeatureNamespace>
                <wfsFeaturePrefix>ad</wfsFeaturePrefix>
                <wfsFeatureType>Address</wfsFeatureType>
                <wfsMaxFeatures>20</wfsMaxFeatures>
                <wfsGeometryElement>ad:position/ad:GeographicPosition/ad:geometry/*</wfsGeometryElement>
                <wfsOutputFormat>text/xml; subtype=gml/3.2.1</wfsOutputFormat>
                <styleMap>
                    <style>
                        <name>default</name>
                        <property>
                            <name>strokeColor</name>
                            <value>#111111</value>
                        </property>
                        <property>
                            <name>fillColor</name>
                            <value>#ffffff</value>
                        </property>
                        <property>
                            <name>strokeWidth</name>
                            <value>1</value>
                        </property>
                        <property>
                            <name>graphicZIndex</name>
                            <value>1</value>
                        </property>
                        <property>
                            <name>fillOpacity</name>
                            <value>0.8</value>
                        </property>
                        <property>
                            <name>pointRadius</name>
                            <value>4</value>
                        </property>
                    </style>
                </styleMap>
            </wfsLayer>
        </context>
    </contextFolder>
</contextCollection>
