=== heron-mc/heron-mc/tags/release-1.0.5/heron/resources/schemas/hmc/1.0/heron-map-context.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema targetNamespace="http://schemas.heron-mc.org/hmc/1.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:hmc="http://schemas.heron-mc.org/hmc/1.0"
	version="1.0" elementFormDefault="qualified">

    <!-- This Schema defines the structure of a Heron Mapping Context or HMC.
         A HMC defines a Map context with a LayerTree. The Map (root) context is called 'contextCollection'.
         The 'contextCollection' defines global Map settings plus a sequence of
         'contextItems'. Basically a LayerTree. Each 'contextItem' is basically a LayerTreeNode and can be a folder (read: folder) or
         or a specific context (read: Layer).

         NB This structure originates from PDOK (www.pdok.nl) and was initially developed by TNO.
         When ported (april 2014) to Heron core the pdok-specific naming was replaced by Heron-naming.
         Also some extra Layer elements were added.
      -->

	<!-- Root element -->
	<xs:element name="contextCollection" type="hmc:contextCollectionType" />

	<xs:element name="contextItem" type="hmc:contextItemType"
		abstract="true" />
	<xs:element name="contextFolder" type="hmc:contextFolderType"
		substitutionGroup="hmc:contextItem" />
	<xs:element name="context" type="hmc:contextType"
		substitutionGroup="hmc:contextItem" />

	<!-- Sub elements -->
	<xs:element name="layer" type="hmc:layerType" abstract="true" />
	<xs:element name="wmsLayer" type="hmc:wmsLayerType"
		substitutionGroup="hmc:layer" />
	<xs:element name="wmtsLayer" type="hmc:wmtsLayerType"
		substitutionGroup="hmc:layer" />
	<xs:element name="tmsLayer" type="hmc:tmsLayerType"
		substitutionGroup="hmc:layer" />
	<xs:element name="wfsLayer" type="hmc:wfsLayerType"
		substitutionGroup="hmc:layer" />
    <xs:element name="atomLayer" type="hmc:atomLayerType"
   		substitutionGroup="hmc:layer" />
    <xs:element name="imageLayer" type="hmc:imageLayerType"
   		substitutionGroup="hmc:layer" />

	<!-- Root type -->
	<xs:complexType name="contextCollectionType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" minOccurs="0" />
            <xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="baseUrl" type="xs:anyURI" minOccurs="0"/>
			<xs:element name="projection" type="xs:string"  minOccurs="0" />
			<xs:element name="units" type="xs:string"  minOccurs="0" />
			<xs:element name="resolutions" type="xs:string"  minOccurs="0" />
			<xs:element name="maxExtent" type="xs:string"  minOccurs="0" />
			<xs:element name="center" type="xs:string"  minOccurs="0" />
			<xs:element name="xyPrecision" type="xs:double"  minOccurs="0" />
			<xs:element name="zoom" type="xs:integer"  minOccurs="0" />
            <!-- Map with no active baseLayer: default is true -->
            <xs:element name="allOverlays" type="xs:boolean" minOccurs="0" />
			<xs:element name="theme" type="xs:anyURI" minOccurs="0" />
			<xs:element ref="hmc:contextItem" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- ContextItem -->
	<xs:complexType name="contextItemType" abstract="true">
		<xs:sequence>
			<xs:element name="isExpanded" type="xs:boolean" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Folder -->
	<xs:complexType name="contextFolderType">
		<xs:complexContent>
			<xs:extension base="hmc:contextItemType">
				<xs:sequence>
					<xs:element name="title" type="xs:string" />
					<xs:element ref="hmc:contextItem" minOccurs="0"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Context -->
	<xs:complexType name="contextType">
		<xs:complexContent>
			<xs:extension base="hmc:contextItemType">
				<xs:choice>
					<xs:sequence>
						<xs:element name="url" type="xs:anyURI" />
					</xs:sequence>
					<xs:sequence>
						<xs:element name="title" type="xs:string" minOccurs = "0" />
						<xs:element name="baseUrl" type="xs:anyURI" minOccurs = "0"/>
						<xs:element ref="hmc:layer" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- Generic Layer -->
	<xs:complexType name="layerType" abstract="true">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="url" type="xs:anyURI" />
			<xs:element name="isBaseLayer" type="xs:boolean" minOccurs="0" />
			<xs:element name="opacity" type="xs:float" minOccurs="0" />
			<xs:element name="isTransparent" type="xs:boolean" minOccurs="0" />
			<xs:element name="isVisible" type="xs:boolean" minOccurs="0" />
			<xs:element name="minResolution" type="xs:float" minOccurs="0" />
			<xs:element name="maxResolution" type="xs:float" minOccurs="0" />
            <xs:element name="attribution" type="xs:string" minOccurs="0" />
            <xs:element name="metadata" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="legend" type="hmc:metadataLegend" minOccurs="0" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
		</xs:sequence>
	</xs:complexType>

	<!-- WMS -->
	<xs:complexType name="wmsLayerType">
		<xs:complexContent>
			<xs:extension base="hmc:layerType">
				<xs:sequence>
					<xs:element name="layers" type="xs:string" />
					<xs:element name="format" type="xs:string" />
					<xs:element name="featureInfoFormat" type="xs:string" />
					<xs:element name="isAlpha" type="xs:boolean" />
					<xs:element name="isSingleTile" type="xs:boolean" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- WMTS -->
	<xs:complexType name="wmtsLayerType">
		<xs:complexContent>
			<xs:extension base="hmc:layerType">
				<xs:sequence>
					<xs:element name="layer" type="xs:string" />
					<xs:element name="style" type="xs:string" />
					<xs:element name="matrixSet" type="xs:string" />
					<xs:element name="matrixIds" type="xs:string" />
					<xs:element name="format" type="xs:string" />
                    <xs:element name="serverResolutions" type="xs:string" minOccurs="0" />
                    <xs:element name="queryable" type="xs:boolean" minOccurs="0" />
                    <xs:element name="featureInfoFormat " type="xs:string" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- TMS -->
	<xs:complexType name="tmsLayerType">
		<xs:complexContent>
			<xs:extension base="hmc:layerType">
				<xs:sequence>
					<xs:element name="layername" type="xs:string" />
					<xs:element name="type" type="xs:string" />
					<xs:element name="bgColor" type="xs:string" />
					<xs:element name="isSingleTile" type="xs:boolean" />
					<xs:element name="isAlpha" type="xs:boolean" />
                    <xs:element name="serverResolutions" type="xs:string" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- WFS -->
	<xs:complexType name="wfsLayerType">
		<xs:complexContent>
			<xs:extension base="hmc:layerType">
				<xs:sequence>
					<xs:element name="wfsVersion" type="xs:string" />
					<xs:element name="wfsFeatureNamespace" type="xs:string" />
                    <xs:element name="wfsFeaturePrefix" type="xs:string" minOccurs="0"/>
					<xs:element name="wfsFeatureType" type="xs:string" />
					<xs:element name="wfsMaxFeatures" type="xs:integer" />
					<xs:element name="wfsGeometryElement" type="xs:string" />
                    <xs:element name="wfsOutputFormat" type="xs:string" minOccurs="0"/>
					<xs:element name="styleMap">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="style" type="hmc:styleType"
									maxOccurs="unbounded">
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

    <!-- Atom feed (GeoRSS) -->
   	<xs:complexType name="atomLayerType">
   		<xs:complexContent>
   			<xs:extension base="hmc:layerType"/>
   		</xs:complexContent>
   	</xs:complexType>

    <!-- Image (ImageLayer) -->
   	<xs:complexType name="imageLayerType">
   		<xs:complexContent>
   			<xs:extension base="hmc:layerType">
   				<xs:sequence>
   					<xs:element name="size" type="xs:string" />
   				</xs:sequence>
   			</xs:extension>
   		</xs:complexContent>
   	</xs:complexType>

	<xs:complexType name="styleType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="property" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" />
						<xs:element name="value" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

    <!-- Metadata for layers -->
    <xs:complexType name="metadataLegend">
        <xs:sequence>
            <xs:element name="legendUrl" type="xs:anyURI" minOccurs="0" />
            <xs:element name="hideInLegend" type="xs:boolean" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== heron-mc/heron-mc/tags/release-1.0.3/heron/examples/heronmapcontext/context/wms/top50vector.xml
<contextCollection xmlns="http://schemas.heron-mc.org/hmc/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://schemas.heron-mc.org/hmc/1.0 http://schemas.heron-mc.org/hmc/1.0/heron-map-context.xsd">
	<context>
			<title>Top50NL Vector</title>
			<wmsLayer>
				<title>Sympoint [wms]</title>
				<url>{baseUrl}top50vector/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<minResolution>13.44</minResolution>
				<maxResolution>26.88</maxResolution>
				<layers>sympoint</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Symline [wms]</title>
				<url>{baseUrl}top50vector/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<minResolution>13.44</minResolution>
				<maxResolution>26.88</maxResolution>
				<layers>symline</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Lijnen [wms]</title>
				<url>{baseUrl}top50vector/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<minResolution>13.44</minResolution>
				<maxResolution>26.88</maxResolution>
				<layers>lijnen</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Huizen [wms]</title>
				<url>{baseUrl}top50vector/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<minResolution>13.44</minResolution>
				<maxResolution>26.88</maxResolution>
				<layers>huizen</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Vlakken [wms]</title>
				<url>{baseUrl}top50vector/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<minResolution>13.44</minResolution>
				<maxResolution>26.88</maxResolution>
				<layers>vlakken</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/tags/release-1.0.4/heron/resources/schemas/hmc/1.0/example2.xml
<?xml version="1.0" encoding="UTF-8"?>
<contextCollection xmlns="http://schemas.heron-mc.org/hmc/1.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://schemas.heron-mc.org/hmc/1.0 http://schemas.heron-mc.org/hmc/1.0/heron-map-context.xsd">

    <title>Thematische PDOK configuratie - Deze configuratie bevat alle services geordend per thema</title>
    <baseUrl>http://test.geodata.nationaalgeoregister.nl/</baseUrl>
    <projection>EPSG:28992</projection>
    <units>m</units>
    <resolutions>3440.640,1720.320, 860.160, 430.080, 215.040, 107.520, 53.760, 26.880, 13.440, 6.720, 3.360, 1.680,
        0.840, 0.420, 0.210, 0.105, 0.0525
    </resolutions>
    <maxExtent>-285401.920,22598.080,595401.920,903401.920</maxExtent>
    <center>155000,463000</center>
    <xyPrecision>3</xyPrecision>
    <zoom>2</zoom>
    <allOverlays>true</allOverlays>

    <context>
        <url>include/achtergrond</url>
    </context>

    <contextFolder>
        <isExpanded>true</isExpanded>
        <title>Adminstratieve eenheden</title>
        <context>
            <url>include/bestuurlijkegrenzen</url>
        </context>
        <context>
            <url>include/wijkenenbuurten</url>
        </context>
    </contextFolder>

    <contextFolder>
        <isExpanded>true</isExpanded>
        <title>Statistiek</title>
        <context>
            <url>include/cbsvierkanten</url>
        </context>
    </contextFolder>

</contextCollection>

=== heron-mc/heron-mc/tags/release-1.0.3/heron/examples/heronmapcontext/context/wms/inspireadressen.xml
<contextCollection xmlns="http://schemas.heron-mc.org/hmc/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://schemas.heron-mc.org/hmc/1.0 http://schemas.heron-mc.org/hmc/1.0/heron-map-context.xsd">
	<context>
		<title>Inspireadressen (=BAG)</title>
		<wmsLayer>
			<title>Adressen [wms]</title>
			<url>{baseUrl}inspireadressen/wms?</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<maxResolution>6.72</maxResolution>
			<layers>inspireadressen</layers>
			<format>image/png</format>
			<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
			<isAlpha>true</isAlpha>
			<isSingleTile>true</isSingleTile>
		</wmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/tags/release-1.0.3/heron/examples/heronmapcontext/context/wms/bodemgebruik2008.xml
<contextCollection xmlns="http://schemas.heron-mc.org/hmc/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://schemas.heron-mc.org/hmc/1.0 http://schemas.heron-mc.org/hmc/1.0/heron-map-context.xsd">
		<context>
			<title>Bodemgebruik 2008</title>
			<wmsLayer>
				<title>BBG eenheden [wms]</title>
				<url>{baseUrl}bestandbodemgebruik2008/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>26.88</maxResolution>
				<layers>bbg2008</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>BBG hoofdgroep [wms]</title>
				<url>{baseUrl}bestandbodemgebruik2008/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<minResolution>53.76</minResolution>
				<layers>bbg2008_hoofdgroep</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
		</context>
</contextCollection>

=== heron-mc/heron-mc/trunk/heron/examples/heronmapcontext/context/wms/aan.xml
<contextCollection xmlns="http://schemas.heron-mc.org/hmc/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://schemas.heron-mc.org/hmc/1.0 http://schemas.heron-mc.org/hmc/1.0/heron-map-context.xsd">
	<context>
		<title>Agrarisch Areaal Nederland (AAN)</title>
		<wmsLayer>
			<title>AAN [wms]</title>
			<url>{baseUrl}aan/wms?</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<maxResolution>26.88</maxResolution>
			<layers>aan</layers>
			<format>image/png</format>
			<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
			<isAlpha>true</isAlpha>
			<isSingleTile>true</isSingleTile>
		</wmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/tags/release-1.0.5/heron/examples/heronmapcontext/context/wms/bevolkingskernen2008.xml
<contextCollection xmlns="http://schemas.heron-mc.org/hmc/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://schemas.heron-mc.org/hmc/1.0 http://schemas.heron-mc.org/hmc/1.0/heron-map-context.xsd">
		<context>
			<title>Bevolkingskernen 2008</title>
			<wmsLayer>
				<title>Naamgeving kernen [wms]</title>
				<url>{baseUrl}bevolkingskernen2008/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>53.76</maxResolution>
				<layers>naamgeving_kernen_alles</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Naamgeving kernen 40k+ [wms]</title>
				<url>{baseUrl}bevolkingskernen2008/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<minResolution>107.52</minResolution>
				<maxResolution>860.16</maxResolution>
				<layers>naamgeving_kernen_40k_plus</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Gemeentegrens generalisatie [wms]</title>
				<url>{baseUrl}bevolkingskernen2008/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<layers>gemeentegrens_generalisatie_2008</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>Provinciegrens generalisatie [wms]</title>
				<url>{baseUrl}bevolkingskernen2008/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<layers>provgrens_generalisatie_2008</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>CBS bevolkingskernen [wms]</title>
				<url>{baseUrl}bevolkingskernen2008/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<layers>cbsbevolkingskernen2008</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
		</context>
</contextCollection>

=== heron-mc/heron-mc/tags/release-1.0.2/heron/examples/heronmapcontext/context/wms/top50raster.xml
<contextCollection xmlns="http://schemas.heron-mc.org/hmc/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://schemas.heron-mc.org/hmc/1.0 http://schemas.heron-mc.org/hmc/1.0/heron-map-context.xsd">
	<context>
		<title>Top50NL Raster</title>
		<wmsLayer>
			<title>Top50NL Raster [wms]</title>
			<url>{baseUrl}top50raster/wms?</url>
			<isBaseLayer>false</isBaseLayer>
			<opacity>0.7</opacity>
			<isTransparent>true</isTransparent>
			<isVisible>false</isVisible>
			<minResolution>13.44</minResolution>
			<maxResolution>26.88</maxResolution>
			<layers>top50raster</layers>
			<format>image/png</format>
			<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
			<isAlpha>true</isAlpha>
			<isSingleTile>true</isSingleTile>
		</wmsLayer>
	</context>
</contextCollection>

=== heron-mc/heron-mc/tags/release-1.0.4/heron/examples/heronmapcontext/context/wms/dtb.xml
<contextCollection xmlns="http://schemas.heron-mc.org/hmc/1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://schemas.heron-mc.org/hmc/1.0 http://schemas.heron-mc.org/hmc/1.0/heron-map-context.xsd">
	<context>
			<title>Digitaal Topografisch Bestand (DTB)</title>
			<wmsLayer>
				<title>DBT Punten [wms]</title>
				<url>{baseUrl}digitaaltopografischbestand/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>13.44</maxResolution>
				<layers>punten</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>DBT Lijnen [wms]</title>
				<url>{baseUrl}digitaaltopografischbestand/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>13.44</maxResolution>
				<layers>lijnen</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
			<wmsLayer>
				<title>DBT Vlakken [wms]</title>
				<url>{baseUrl}digitaaltopografischbestand/wms?</url>
				<isBaseLayer>false</isBaseLayer>
				<opacity>0.7</opacity>
				<isTransparent>true</isTransparent>
				<isVisible>false</isVisible>
				<maxResolution>13.44</maxResolution>
				<layers>vlakken</layers>
				<format>image/png</format>
				<featureInfoFormat>application/vnd.ogc.gml</featureInfoFormat>
				<isAlpha>true</isAlpha>
				<isSingleTile>true</isSingleTile>
			</wmsLayer>
	</context>
</contextCollection>
